version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      npm:
        patterns:
          - '*'
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "tchssk"
